Add remaining fields to drainagestrategy
equinor/dcd pull request #107
Opened 2022-01-17 11:18 UTC by petterwildhagen

2022-01-17 15:56 UTC, valentin-krasontovitsch requested changes
sorry, quite a few comments, but hopefully just minor questions : )

2022-01-17 15:56 UTC, valentin-krasontovitsch commented on backend/api/Models/DrainageStrategy.cs
> +using Microsoft.EntityFrameworkCore.Metadata.Internal;
I'm so sorry, i'm trying a bit of a thorough review, and you're receiving all these possibly silly comments / questions, so please bear with me (hopefully just a bit longer) - how come you added this second using statement? based on the other added lines in this file, i don't see anything "conceptually new" that would require an additional `using` added, and indeed in a quick test the code builds with that using statement commented out.

2022-01-17 15:56 UTC, valentin-krasontovitsch commented on backend/tests/Services/ProjectService.cs
> +                var yearValuePairsXY = expected.YearValues.OrderBy(v => v.Year).Zip(actual.YearValues.OrderBy(v => v.Year));
does it make sense to compare the length of both lists? based on the docs it seems like if one of the list is a proper sublist of the other, this test will not fail. or is that what we want?

2022-01-18 08:22 UTC, petterwildhagen commented on backend/api/Context/TestDataBuilder.cs
> +    public Co2EmissionsBuilder WithYearValue(int y, double v)
Fixed

2022-01-18 08:26 UTC, petterwildhagen commented on backend/api/Models/TimeSeries.cs
>          BBL
The code should be self documenting so ideally no explanation or inline comments. The domain model should be a description of the domain. So leave as is for now.

2022-01-18 08:27 UTC, petterwildhagen commented on backend/api/Models/DrainageStrategy.cs
> +using Microsoft.EntityFrameworkCore.Metadata.Internal;
See line 12, this is needed for the foreign key statement

2022-01-18 08:34 UTC, petterwildhagen commented on backend/tests/Services/ProjectService.cs
> +                var yearValuePairsXY = expected.YearValues.OrderBy(v => v.Year).Zip(actual.YearValues.OrderBy(v => v.Year));
Yes, it makes sense. Fixed.

2022-01-18 08:36 UTC, petterwildhagen commented on backend/api/Context/TestDataGenerator.cs
> +                    })
Ah - I forgot to add year values. Fixed.

2022-01-18 09:56 UTC, petterwildhagen commented on backend/api/Models/Co2Emissions.cs
> +        [ForeignKey("DrainageStrategy.Id")]
The foreign key specifies which entity is the dependent one.

2022-01-18 10:06 UTC, valentin-krasontovitsch approved these changes
thanks for the answers and fixes!

2022-01-18 10:10 UTC, valentin-krasontovitsch approved these changes

2022-01-18 10:11 UTC, merged