Calculate cash flow
equinor/dcd pull request #1281
Opened 2024-09-23 11:29 UTC by JonasABach

2024-10-04 09:40 UTC, JonasABach commented on backend/api/Program.cs
> +using api.Dtos;
I need this for builder.Services.AddScoped<IEconomicsCalculationHelper, EconomicsCalculationHelper>();

2024-10-04 09:52 UTC, JonasABach commented on backend/api/Context/DcdDbContext.cs
> +using api.Helpers;
for these             await _serviceProvider.GetRequiredService<IEconomicsCalculationHelper>().CalculateTotalIncome(caseId);

2024-10-09 08:30 UTC, taustad requested changes

2024-10-09 08:30 UTC, taustad commented on backend/api/Helpers/EconomicsCalculationHelper.cs
> +namespace api.Helpers
This looks more like a service than a helper. Helpers should in most cases be static. Move this to the services namespace

2024-10-09 08:30 UTC, taustad commented on backend/api/Context/DcdDbContext.cs
> +        var surfChanges = ChangeTracker.Entries<Models.Surf>()
Pull the latest main and you don't have to specify Models.Surf anymore

2024-10-09 08:30 UTC, taustad commented on backend/api/Context/DcdDbContext.cs
> +        }
What are the nested ifs for? Should we not look for changes to affected entities with CalculateNPV() or CalculateBreakEvenOilPrice()?

If they always need to be calculated after total income the ifs are unnecessary

2024-10-09 08:30 UTC, taustad commented on backend/api/Context/DcdDbContext.cs
> +        }
See comment above

Is NPV and BreakEven used in the total cost calculation? Is there any reason to run this twice if both TotalCost and TotalIncome is true?

2024-10-09 08:30 UTC, taustad commented on backend/api/Context/DcdDbContext.cs
> +        }
Instead of running the calculations in the nested ifs, would it work to just set the rerunCaclulateNPV and rerunCalculateBreakEven to true in the nested ifs and run them once at the end?

2024-10-09 08:30 UTC, taustad commented on backend/api/Services/Entities/Case/CaseTimeSeriesService.cs
> +    }
Are these ever used?

2024-10-09 08:30 UTC, taustad commented on backend/api/Repositories/Case/CaseTimeSeriesRepository.cs
> +    }
Is this used anywhere?

2024-10-09 08:30 UTC, taustad commented on backend/api/Repositories/Case/CaseTimeSeriesRepository.cs
> +    }
Is this used anywhere?

2024-10-09 08:30 UTC, taustad commented on backend/api/Repositories/Case/CaseTimeSeriesRepository.cs
> +    }
Is this used anywhere?

2024-10-09 08:30 UTC, taustad commented on backend/api/Services/GenerateCostProfiles/OpexCostProfileService.cs
>          }
Does this work as intended?

2024-10-09 08:43 UTC, taustad commented on backend/api/Helpers/EconomicsCalculationHelper.cs
> +            var wellProject = await _wellProjectRepository.GetWellProject(caseItem.WellProjectLink);
Need to include the profiles you need in GetWithIncludes

2024-10-09 08:43 UTC, taustad commented on backend/api/Helpers/EconomicsCalculationHelper.cs
> +            var explorationCost = await _explorationRepository.GetExploration(caseItem.ExplorationLink);
Need to include the profiles you need in GetWithIncludes

2024-10-09 08:43 UTC, taustad commented on backend/api/Helpers/EconomicsCalculationHelper.cs
> +            var transport = await _transportRepository.GetTransport(caseItem.TransportLink);
Need to include the profiles you need in GetWithIncludes

2024-10-09 08:45 UTC, taustad commented on backend/api/Helpers/EconomicsCalculationHelper.cs
> +            var transport = await _transportRepository.GetTransport(caseItem.TransportLink);
Send these as parameters and you can make the method a static helper method

2024-10-09 08:45 UTC, taustad commented on backend/api/Helpers/EconomicsCalculationHelper.cs
> +            var wellProject = await _wellProjectRepository.GetWellProject(caseItem.WellProjectLink);
Send these as parameters and you can make the method a static helper method

2024-10-09 08:45 UTC, taustad commented on backend/api/Helpers/EconomicsCalculationHelper.cs
> +            var explorationCost = await _explorationRepository.GetExploration(caseItem.ExplorationLink);
Send these as parameters and you can make the method a static helper method

2024-10-09 08:47 UTC, taustad commented on backend/api/Helpers/EconomicsCalculationHelper.cs
> +        private readonly IDrainageStrategyRepository _drainageStrategyRepository;
Remove

2024-10-09 11:31 UTC, JonasABach commented on backend/api/Services/GenerateCostProfiles/OpexCostProfileService.cs
>          }
testet, og det ser ut som det fungerer.

2024-10-15 13:29 UTC, taustad approved these changes

2024-10-16 07:39 UTC, merged