Added service and controller for Surf
equinor/dcd pull request #171
Opened 2022-01-27 17:52 UTC by eiriksanderfjeld

Added both controller and service based on Exploration. #154

2022-01-31 12:47 UTC, petterwildhagen requested changes
Fix codacy errors and take a look at Eric PR (soon to be merged to main) for splitting up db context for unit tests.

2022-02-01 11:42 UTC, ericnorway commented on backend/api/Dtos/SurfDto.cs
> +    public enum ProductionFlowlineDto
I think this can be removed.

2022-02-01 11:42 UTC, ericnorway commented on backend/api/Services/SurfService.cs
> +                var result = _context.Surfs.Add(surf);
I think the new surf needs to be added to the project's surf collection.

2022-02-01 11:42 UTC, ericnorway commented on backend/api/Services/SurfService.cs
> +                var result = _context.Surfs.Remove(surf);
And removed from the project's surfs collection.

2022-02-01 15:03 UTC, ericnorway submitted a review, later dismissed
approved

2022-02-01 15:31 UTC, closed without merging