Update dashboard
equinor/dcd pull request #280
Opened 2022-02-16 10:00 UTC by valentin-krasontovitsch

Closes #270

2022-02-18 11:12 UTC, aronhoyer requested changes

2022-02-18 11:12 UTC, aronhoyer commented on frontend/src/Views/DashboardView.tsx
> +        const recentProjectsWithTimeStamp = projects.map( project => {
let's have a look at how we're storing recently accessed projects.

2022-02-20 19:47 UTC, valentin-krasontovitsch commented on frontend/src/Components/RecentProjects.tsx
> +        const backgroundColor = phase === undefined ?
thank you, fixed! love the fuzzyness of falsy : )

2022-02-20 20:02 UTC, valentin-krasontovitsch commented on frontend/src/Components/RecentProjects.tsx
> +    const renderProjectDG = (phase: Components.Schemas.ProjectPhase | undefined) => {
ah, nice, thank you, fixed!

2022-02-20 20:03 UTC, valentin-krasontovitsch commented on frontend/src/Components/RecentProjects.tsx
> +    const renderDescription = (description: string | null | undefined) => {
fixed

2022-02-20 20:05 UTC, valentin-krasontovitsch commented on frontend/src/Components/RecentProjects.tsx
> +    if (!projects || projects.length === 0) return null
thanks again! such a yummy feature ^^ fixed.

2022-02-20 20:07 UTC, valentin-krasontovitsch commented on frontend/src/Components/RecentProjects.tsx
> +    const renderDescription = (description: string | null | undefined) => {
ah i had to keep the null in there, as `description` has the type `string? | null` in `types.d.ts` (and i get an error if i remove it)

2022-02-20 20:12 UTC, valentin-krasontovitsch commented on frontend/src/Components/RecentProjects.tsx
> +                {projects.map((project) => { return (
thanks, fixed! those details around arrow functions and when you can skip the return, i'm always hazy on them...

2022-02-20 20:12 UTC, valentin-krasontovitsch commented on frontend/src/Components/RecentProjects.tsx
> +                {projects.map((project) => { return (
thanks, fixed! those details around arrow functions and when you can skip the return, i'm always hazy on them...

2022-02-20 20:14 UTC, valentin-krasontovitsch commented on frontend/src/Views/DashboardView.tsx
> +        const recentProjectsWithTimeStamp = projects.map( project => {
sure thing!

2022-02-21 08:49 UTC, aronhoyer submitted a review, later dismissed
looks good! we'll update storage strategy once the demo is done.

merge once we resolve snyk error.

2022-02-21 13:18 UTC, aronhoyer approved these changes

2022-02-21 13:18 UTC, merged