wip add new project
equinor/dcd pull request #291
Opened 2022-02-18 10:14 UTC by ericnorway

2022-02-18 11:56 UTC, aronhoyer requested changes

2022-02-18 11:56 UTC, aronhoyer commented on frontend/src/Components/Modal.tsx
> +                    <Button onClick={handleOkClick}>{okButtonText}</Button>
i'm not sure we necessarily want only the `onClick` handler and button texts. i think we're better served with passing the actual button as props (i.e. we pass a component as a prop)

2022-02-18 11:56 UTC, aronhoyer commented on frontend/src/Utils/common.tsx
> +    Null = 0,
you don't need to explicitly assign values to enum keys if the values are just `0..n`. that's the default 😄

2022-02-18 11:56 UTC, aronhoyer commented on frontend/src/Views/CreateProjectView.tsx
> +        if (commonLibraryService) {
no need for this check

2022-02-18 11:56 UTC, aronhoyer commented on frontend/src/Services/ProjectService.ts
> +    postProject(project: Components.Schemas.ProjectDto) {
let's try to stier away from using http verbs in service methods. "insert" or "create" are better options.

2022-02-18 11:56 UTC, aronhoyer commented on frontend/src/Services/__BaseService.ts
> +            'Content-type': 'application/json',
there's no need to explicitly set this. axios should be able to infer this based on the request body type. that being said, body (as defined on line 34) should not be a string, but passed raw. there's also a change to this coming with my branch on the ProjectView implementation, so you don't necessarily need to update this right now. have a look at [the commit](https://github.com/aronhoyer/dcd/commit/1b5b916c102e2f5fefcbc2e533059d3459ecb285) if you want to sync with how i've implemented the changes to the BaseService

2022-02-18 11:56 UTC, aronhoyer commented on frontend/src/Views/CreateProjectView.tsx
> +    const [selectedProject, setSelectedProject] = useState<Components.Schemas.CommonLibraryProjectDto>();
let's look into implementing [react hook form](https://www.npmjs.com/package/react-hook-form) instead of handling form state ourselves. forms re-evaluations and re-renders can quickly get out of hand.

2022-02-18 11:56 UTC, aronhoyer commented on frontend/src/Views/CreateProjectView.tsx
> +                    <Icon data={search} color={grey}></Icon>
when a component doesn't have children, it's considered self closing, so instead of writing `<Icon></Icon>` we can write `<Icon />`

2022-02-18 11:56 UTC, aronhoyer commented on frontend/src/Views/CreateProjectView.tsx
> +                    <Label htmlFor="textfield-name" label="Name" />
prefer `<TextField />` over `<Label />` and `<Input />`. take a look at the [eds storybook](https://eds-storybook-react.azurewebsites.net/?path=/story/introduction--page)

2022-02-18 11:56 UTC, aronhoyer commented on frontend/package.json
> +        "react-focus-lock": "^2.8.1",
prefer [react focus on](https://www.npmjs.com/package/react-focus-on)

2022-02-21 11:46 UTC, ericnorway commented on frontend/src/Views/CreateProjectView.tsx
> +    const [selectedProject, setSelectedProject] = useState<Components.Schemas.CommonLibraryProjectDto>();
Will look into this after the demo.

2022-02-21 13:17 UTC, aronhoyer requested changes
looks good overall. just one more change and we can merge it. 👍

2022-02-21 13:17 UTC, aronhoyer commented on frontend/src/Services/__BaseService.ts
> +    protected post<T = any>(path: string, body?: Record<string, any>, options?: RequestOptions): Promise<T> {
`body` is still in the parameter list. since it's accessible through the `options` object, the `body` parameter is superfluous. removing it from the parameter list also allows for not having to explicitly pass it on in the `this.request` call on line 51.

2022-02-21 13:51 UTC, aronhoyer approved these changes

2022-02-21 14:13 UTC, aronhoyer approved these changes

2022-02-21 14:14 UTC, merged