E2e tests
equinor/dcd pull request #295
Opened 2022-02-20 20:35 UTC by valentin-krasontovitsch

2022-02-22 16:47 UTC, valentin-krasontovitsch commented
Ready for review!

I'm sorry, there's quite a bit that has happened in this PR - but I grouped the changes into hopefully kindof atomically scoped commits, so if you don't just look at the changes but rather look at the commits and their respective changes, it should be easier to understand what's going on.

also the first couple commits up to the e2e tests we have already discussed : )

i'll be available for questions and comments or discussions

2022-02-25 13:36 UTC, petterwildhagen requested changes
Excellent!!!
Just fix the minor bug with the create date when returning the project from the project Dto.
There are also some codacy errors that should be fixed.

2022-02-25 13:36 UTC, petterwildhagen commented on backend/api/Adapters/ProjectAdapter.cs
> +            project.CreateDate = DateTimeOffset.UtcNow;
Only set create date if not already set. Otherwise the date is updated everytime this method gets called (creating an object to send to the backend).

2022-02-26 21:08 UTC, valentin-krasontovitsch commented on backend/api/Adapters/ProjectAdapter.cs
> +            project.CreateDate = DateTimeOffset.UtcNow;
very good point, thank you!

actually i'm wondering... which create day exactly are we trying to model here? the date on which a project gets created in our app? or the date on which a project was created according to commonlib? maybe we can discuss this a bit on monday

because if we say we only set the date if it's not set on the project dto, then we should make it optional on the project dto. then the question becomes in which cases do we expect to receive a created date in the project dto? if we only ever receive a project dto as part of the create project endpoint, and if we say that all projects have to come from commonlib do we sometimes import a creation date from commonlib, sometimes not? but if the adapter possibly gets used by other endpoints as well, then we should maybe move the setting of the date for the create project use-case to the service or the controller?!

2022-02-28 08:23 UTC, petterwildhagen commented on backend/api/Adapters/ProjectAdapter.cs
> +            project.CreateDate = DateTimeOffset.UtcNow;
Correction: The create date has to be set -- obviously -- be set when project is created.

2022-02-28 08:43 UTC, petterwildhagen commented on backend/tests/Adapters/DrainageStrategyAdapterShould.cs
>          {
This file can be deleted

2022-02-28 09:22 UTC, petterwildhagen commented on backend/api/Adapters/ProjectAdapter.cs
> +            project.CreateDate = DateTimeOffset.UtcNow;
So simply set the date here:
![image](https://user-images.githubusercontent.com/16671886/155957399-2ac915d2-98bd-411e-8f07-7bb64cc6cff5.png)

2022-02-28 14:00 UTC, valentin-krasontovitsch commented on backend/api/Adapters/ProjectAdapter.cs
> +            project.CreateDate = DateTimeOffset.UtcNow;
fixed!

2022-02-28 14:49 UTC, valentin-krasontovitsch commented on backend/tests/Adapters/DrainageStrategyAdapterShould.cs
>          {
I disagree with deleting any unit tests for now - we have not covered all our bases with the end to end tests yet. we need both more test scenarios, and more varied test data before we can be sure that all services and adapters all covered by e2e tests, and then we can delete the unit tests which at the moment cover services and adapters.

2022-03-01 09:25 UTC, valentin-krasontovitsch commented
@petterwildhagen i btw also checked if these changes have any effects on the frontend by rebuilding and comparing the automatically generated models file - they don't, the frontend should be unaffected by the changes in this PR (i mean it won't break anything)

2022-03-01 10:41 UTC, petterwildhagen approved these changes
Looks good!

2022-03-01 11:06 UTC, merged