Update recent projects storage strategy
equinor/dcd pull request #357
Opened 2022-03-02 12:55 UTC by valentin-krasontovitsch

closes #296

2022-03-03 08:36 UTC, aronhoyer commented on frontend/src/Components/RecentProjects.tsx
> +        const labelText = phase || "TBD"
for this case this might be what we want, but something to keep in mind with the logical or operator, is that a lot of values are evaluated as `false` in javascript. for example, and empty string is evaluated as `false` (0 is as well), which in some cases might lead to unintended behaviour of our program. for those cases we can use the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator). just something to keep in mind :)

2022-03-03 08:44 UTC, aronhoyer requested changes
i don't know about having a separate model for a recently visited project. essentially it's just a project, so by having two models, we're basically duplicating code and maintenance.

what was your reasoning behind creating a separate model for it?

2022-03-03 08:44 UTC, aronhoyer commented on frontend/src/Utils/common.tsx
> +export function RetrieveRecentProjects() {
this can be a static method on the new `RecentProject` model

2022-03-03 08:44 UTC, aronhoyer commented on frontend/src/Utils/common.tsx
> +export function StoreRecentProject(project: Project) {
this can be an method on the new `RecentProject` model

2022-03-03 09:26 UTC, valentin-krasontovitsch commented on frontend/src/Components/RecentProjects.tsx
> +        const labelText = phase || "TBD"
thanks, will keep it in mind!

2022-03-03 09:31 UTC, valentin-krasontovitsch commented
> what was your reasoning behind creating a separate model for it?

@aronhoyer one of the goals with the restructuring was to store only the information needed for the recent project card - rather than explicitly listing the properties we want when we store, retrieve, and render, it seemed elegant to gather the information. maybe it shouldn't be its own "model", just a type, or class, or something, but i'm not familiar with the naming conventions...
i can break it up into the particular fields though, but i think it makes the code more cumbersome?
do you have a suggestion for solving this?

2022-03-07 12:41 UTC, ahmedoabdi commented
Any thoughts or updates regarding the last comment @aronhoyer?

2022-03-08 08:36 UTC, aronhoyer commented
> do you have a suggestion for solving this?

i don't know if i said this, but in order to get around the duplicate model issue, we could store an array of Projects. to reduce the payload size, maybe we could have a generalized util function to clear out object fields that have nullish or falsy values.

2022-03-08 10:38 UTC, valentin-krasontovitsch commented
ok cool i can do that, for sure. i'm gonna 

- store projects in the array
- make the store and retrieve functions methods on the project type

but i'm a bit uncertain as to what you exactly mean by clearing out object fields that have falsy or nullish values - i thought maybe just stripping assets, as they are not used in this context and are potentially large, as in settings those to `null`, but that's not what you mean, right?

2022-03-08 10:46 UTC, aronhoyer commented
@valentin-krasontovitsch not what i meant, but we should definitely strip any values from the object that are not pertinent to displaying a recently visited project

2022-03-08 11:45 UTC, valentin-krasontovitsch commented
OK, gotcha I think.

another issue - it seems like the "complex" types don't properly survive being stored as JSON and then parsed again - in the code, everything is fine typewise, but when I try to for instance run the `toString` function on an instance of `ProjectPhase`, I just get `[object Object]` instead of the expected. Also, the createdAt does not come back as a `Date`, but rather as a string after parsing it from JSON.

any pointers, @aronhoyer?

2022-03-08 11:48 UTC, aronhoyer commented
use `JSON.stringify` instead of `toString` :)

2022-03-08 12:10 UTC, valentin-krasontovitsch commented
oh i use `stringify` when storing the projects - `toString` is a method of the projectphase type, which translates the number to a phase string. it seems like i had to use custom parsing of JSON to get back `Date` and `Phase`, passing an extra function as second argument to `JSON.parse` when retrieving the stringified projects from localstorage. gonna push the new changes soon

2022-03-08 12:50 UTC, valentin-krasontovitsch commented on frontend/src/Utils/common.tsx
> +export function RetrieveRecentProjects() {
done on Project model

2022-03-08 12:50 UTC, valentin-krasontovitsch commented on frontend/src/Utils/common.tsx
> +export function StoreRecentProject(project: Project) {
done on Project model

2022-03-08 13:01 UTC, aronhoyer approved these changes

2022-03-08 13:03 UTC, merged