Feature/332 create topside asset
equinor/dcd pull request #437
Opened 2022-03-25 13:18 UTC by ManveerPandher

Reason for case:
- When creating a project, there should be possible to assign a current or existing "Topside", aswell as edit the content.

What has been done:
- Replicated the way Substructure Asset was created with its own View, and added existing fields to datamodels within Frontend and Backend

2022-03-25 14:24 UTC, petterwildhagen commented on frontend/src/Views/TopsideView.tsx
> +        console.log("Before copying")
Delete console log debug statements?

2022-03-25 14:53 UTC, petterwildhagen requested changes
Looks good, just delete the console log statements and I will approve

2022-03-28 07:16 UTC, ManveerPandher commented on frontend/src/Views/TopsideView.tsx
> +        console.log("Before copying")
@petterwildhagen 
I've deleted the console log debug statemtents

2022-03-28 07:28 UTC, petterwildhagen approved these changes
Looks good

2022-03-28 11:22 UTC, petterwildhagen approved these changes
Looks good!!!

2022-03-28 14:14 UTC, merged