Feature/494 add cessation cost to offshore facilities - DO NOT MERGE
equinor/dcd pull request #515
Opened 2022-04-07 10:16 UTC by ManveerPandher

DO NOT TOUCH.
DO NOT MERGE.

2022-04-11 15:46 UTC, taustad requested changes
Please fix "cessasion" -> "cessation"
Also remove redundant null checks in adapters
We should probably discuss using var instead of type for variables

2022-04-11 15:46 UTC, taustad commented on backend/api/Adapters/SubstructureAdapter.cs
> +            }
Why check for null here? There is a null check in the Convert method

2022-04-11 15:46 UTC, taustad commented on backend/api/Adapters/SubstructureAdapter.cs
> +            }
Why check for null here? There is a null check in the Convert method

2022-04-11 15:46 UTC, taustad commented on backend/api/Adapters/SurfAdapter.cs
> +            }
Why check for null here? There is a null check in the Convert method

2022-04-11 15:46 UTC, taustad commented on frontend/src/Views/SubstructureView.tsx
> +                <Typography variant="h4">Cessasion Cost profile</Typography>
Spelling

2022-04-12 11:24 UTC, ManveerPandher commented on backend/api/Adapters/SubstructureAdapter.cs
> +            }
Fixed

2022-04-12 11:24 UTC, ManveerPandher commented on backend/api/Adapters/SubstructureAdapter.cs
> +            }
Fixed

2022-04-12 11:24 UTC, ManveerPandher commented on backend/api/Adapters/SubstructureAdapter.cs
> +            SubstructureCessasionCostProfile substructureCessasionCostProfile = new SubstructureCessasionCostProfile
Another day

2022-04-12 11:25 UTC, ManveerPandher commented on backend/api/Adapters/SurfAdapter.cs
> +            }
Fixed

2022-04-12 11:25 UTC, ManveerPandher commented on backend/api/Adapters/SurfAdapter.cs
> +            }
Fixed

2022-04-12 11:25 UTC, ManveerPandher commented on backend/api/Context/DcdDbContext.cs
> +        public DbSet<TopsideCessasionCostProfile>? TopsideCessasionCostProfiles { get; set; }
Fixed

2022-04-12 11:25 UTC, ManveerPandher commented on frontend/src/Views/SubstructureView.tsx
> +                const newCessasionCostProfileColumnTitles = getColumnAbsoluteYears(
Fixed

2022-04-12 11:25 UTC, ManveerPandher commented on frontend/src/Views/SubstructureView.tsx
> +                <Typography variant="h4">Cessasion Cost profile</Typography>
Fixed

2022-04-12 11:25 UTC, ManveerPandher commented on frontend/src/models/assets/substructure/Substructure.ts
> +import { SubstructureCessasionCostProfile } from "./SubstructureCessasionCostProfile"
Fixed

2022-04-12 11:27 UTC, ManveerPandher commented
Fixed comments from QA

2022-04-12 11:28 UTC, taustad submitted a review, later dismissed

2022-04-20 08:23 UTC, petterwildhagen approved these changes
LGTM! The few very minor issues can be addressed in separate PR (parenthesis, var instead of class name)

2022-04-20 08:24 UTC, merged