Added ArtificialLift to case
equinor/dcd pull request #555
Opened 2022-04-25 09:07 UTC by fredrikleknes

2022-04-25 09:34 UTC, taustad requested changes

2022-04-25 09:34 UTC, taustad commented on frontend/src/Components/CaseArtificialLift.tsx
> +    setArtificialLift: React.Dispatch<React.SetStateAction<Components.Schemas.ArtificialLift | undefined>>,
Import Dispatch and SetStateAction and use them directly instead of React.Dispatch and React.SetStateAction

2022-04-25 09:52 UTC, fredrikleknes commented on frontend/src/Components/CaseArtificialLift.tsx
> +    setArtificialLift: React.Dispatch<React.SetStateAction<Components.Schemas.ArtificialLift | undefined>>,
Done!

2022-04-26 06:44 UTC, taustad approved these changes
LGTM

2022-04-26 06:45 UTC, merged