Get project ids in org chart context
equinor/dcd pull request #66
Opened 2022-01-10 14:16 UTC by maiaht

2022-01-26 12:29 UTC, maiaht commented on frontend/src/Services/useService.ts
>          }
This does not work. For instance will `ProjectService.getProjectByID(params.projectId!)` fail since `ProjectService` is given by `const ProjectService = useService('ProjectService')` and `useService()` returns the type `__FusionService | __ProjectService | undefined`. The error will then be that `getProjectByID` does not exist on the type `__FusionService`.

2022-01-26 12:34 UTC, maiaht commented
I don't know why there are changes in `package-lock.json`. The `package-lock.json` that is shown here is what I get when I do `npm install` based on the `package.json` on master.

2022-01-27 07:35 UTC, aronhoyer commented on frontend/src/Services/FusionService.ts
> +export const useFusionService = () => {
what's the idea behind sticking with a custom hook here? by doing this, we'll send a network call for every time this hook is called.

2022-01-28 10:18 UTC, aronhoyer commented on frontend/src/Services/FusionService.ts
> +export const FusionService = () => {
why are the service classes wrapped in functions? do we need to be able to make new instances for each time we want to consume a service's api?

2022-01-28 10:19 UTC, aronhoyer commented on frontend/src/Services/config.ts
> +        BASE_URL: `https://pro-s-context-fprd.azurewebsites.net`
I assume this won't change between the dev, qa and prod environments?

2022-01-28 10:38 UTC, aronhoyer requested changes

2022-01-28 10:38 UTC, aronhoyer commented on frontend/src/Components/SideMenu/SideMenu.tsx
> +        if (projectService && params.projectId) {
checking for whether the service exists or not isn't really necessary.

2022-01-28 12:02 UTC, maiaht commented on frontend/src/Services/FusionService.ts
> +export const useFusionService = () => {
Fixed

2022-01-28 12:02 UTC, maiaht commented on frontend/src/Services/FusionService.ts
> +export const FusionService = () => {
Fixed

2022-01-28 12:02 UTC, maiaht commented on frontend/src/Components/SideMenu/SideMenu.tsx
> +        if (projectService && params.projectId) {
Fixed

2022-01-30 18:32 UTC, petterwildhagen submitted a review, later dismissed
I am not sure if the frontend should integrate with Org chart as we are not sure what role the front end will play in the architecture. It might have to be the back end that integrates with Org chart --- we will know this once we know more about the requirements and hence the over all architecture.

2022-02-01 08:19 UTC, aronhoyer approved these changes

2022-02-01 08:23 UTC, merged