Add producerCount, WaterInjectorCount, gasInjectorCount to Surf PROSP import
equinor/dcd pull request #689
Opened 2022-06-23 12:24 UTC by petterwildhagen

2022-06-23 12:45 UTC, ahmedoabdi requested changes
Check comment on gas- and water-injector

2022-06-23 13:24 UTC, petterwildhagen commented on backend/api/Services/ImportProspService.cs
> +            var waterInjectorCount = ReadIntValue(cellData, "E40");
Good catch. Fixed

2022-06-24 06:20 UTC, ahmedoabdi commented on backend/api/Services/ImportProspService.cs
> +            var waterInjectorCount = ReadIntValue(cellData, "E40");
Tested, works well. Nice job 👍🏿

2022-06-24 06:20 UTC, ahmedoabdi approved these changes
LGTM!

2022-06-24 06:22 UTC, merged