Duplicate case from project overview
equinor/dcd pull request #723
Opened 2022-08-11 10:12 UTC by DanielBohme

2022-08-11 12:01 UTC, taustad commented on frontend/src/Views/CasesTableView.tsx
> +                const newProject: Project = await (await GetCaseService()).duplicateCase(caseRowDataSelected.id, {})
Should you not set the new project after retrieving it from the server?

2022-08-11 12:11 UTC, taustad commented on frontend/src/Views/CasesTableView.tsx
> +                const newProject: Project = await (await GetCaseService()).duplicateCase(caseRowDataSelected.id, {})
Why specify the type when duplicateCase returns a Promise<Project>?

2022-08-16 05:42 UTC, taustad commented on frontend/src/Services/CaseService.ts
> +    public async duplicateCase(copyCaseId: any, data: Components.Schemas.CaseDto): Promise<Project> {
Why datatype any for copyCaseId?

2022-08-16 05:45 UTC, taustad commented on frontend/src/Views/CasesTableView.tsx
> +    const [, setProject] = useState<Project>()
Pass the setProject function from the view in order for the component to rerender when you duplicate a case.

2022-08-16 05:45 UTC, taustad commented on frontend/src/Views/CasesTableView.tsx
> +                const projectResult = await (await GetProjectService()).getProjectByID(fusionProjectId!)
What is the purpose of this?

2022-08-16 05:46 UTC, taustad requested changes
See comments

2022-08-16 08:35 UTC, DanielBohme commented on frontend/src/Services/CaseService.ts
> +    public async duplicateCase(copyCaseId: any, data: Components.Schemas.CaseDto): Promise<Project> {
datatype is any due to the object: 
![image](https://user-images.githubusercontent.com/52354696/184835576-50704672-386b-4090-9f51-39f36942b7e0.png)

2022-08-16 09:57 UTC, taustad commented on frontend/src/Services/CaseService.ts
> +    public async duplicateCase(copyCaseId: any, data: Components.Schemas.CaseDto): Promise<Project> {
Isn't copyCaseId just the id of the case?

2022-08-17 09:42 UTC, taustad commented on backend/api/Services/CaseService.cs
> +                if (c.Name.Contains(case_.Name))
Not a serious bug, but if you have a case named "Test" and a case named "T", and you duplicate "T" it will be named "T - copy #2" and not "T - copy #1"

Here is an example with more values
![Capture123123](https://user-images.githubusercontent.com/100409988/185087662-9a8395e6-36f6-45c3-a2a6-29c0092cb787.PNG)

2022-08-17 09:43 UTC, taustad commented on backend/api/Services/CaseService.cs
> +                if (c.Name.Contains(case_.Name))
Check for equality and not contains

2022-08-17 09:47 UTC, taustad requested changes
See comment

2022-08-18 09:55 UTC, DanielBohme commented on backend/api/Services/CaseService.cs
> +                if (c.Name.Contains(case_.Name))
Changed to equality even though it looks ugly. Not able to replicate "T" name copy bug after equality implementation.

2022-08-18 10:09 UTC, taustad commented on backend/api/Services/CaseService.cs
> +                string lastCharInName = c.Name.Substring(c.Name.Length - 1, 1);
What happens if there are 10 copies or more?

2022-08-18 10:09 UTC, taustad commented on backend/api/Services/CaseService.cs
> +                var isNum = int.TryParse(lastCharInName, out copyNumber);
Where is "isNum" used?

2022-08-18 10:10 UTC, taustad commented on backend/api/Services/CaseService.cs
> +                string lastCharInName = c.Name.Substring(c.Name.Length - 1, 1);
Why are some variables declared with type some with var?

2022-08-18 10:18 UTC, DanielBohme commented on backend/api/Services/CaseService.cs
> +                var isNum = int.TryParse(lastCharInName, out copyNumber);
Woops. This isn't the correct version. Will update to correct one

2022-08-18 10:22 UTC, DanielBohme commented on backend/api/Services/CaseService.cs
> +                string lastCharInName = c.Name.Substring(c.Name.Length - 1, 1);
That is true. If copies go beyond 10, the next copies beyond that will all be named copy nr 10. Will have to check how much needs to be put into this. If beyond 10 copies is relevant

2022-08-18 10:27 UTC, taustad approved these changes
LGTM

2022-08-18 10:32 UTC, merged