Case table - open case, edit case, removed top line in side menu
equinor/dcd pull request #728
Opened 2022-08-15 10:47 UTC by DanielBohme

Case can now be opened and edited in the case table menu.
Top line in side menu has been removed.

2022-08-16 05:17 UTC, taustad commented on frontend/src/Views/CasesTableView.tsx
> +            const projectResult: Project = await (await GetCaseService()).updateCase({
Why not set the project after updating?

2022-08-16 05:30 UTC, taustad commented on frontend/src/Views/CasesTableView.tsx
> +            })
Why create a new Case object instead of spreading the existing one? If you do it this way you lose all the data other than what you specify.

2022-08-16 05:32 UTC, taustad commented on frontend/src/Views/CasesTableView.tsx
> +                        placeholder={caseRowDataSelected?.name ?? "Enter a name"}
Should we not keep the existing value for each case, so that we don't have to add both name and description when chaning name?

2022-08-16 05:34 UTC, taustad commented on frontend/src/Views/CasesTableView.tsx
>  /* eslint-disable @typescript-eslint/no-unused-vars */
Try to remove unnecessary eslint-disables, or make it so they aren't necessary

2022-08-16 05:34 UTC, taustad requested changes
See comments

2022-08-16 05:52 UTC, taustad commented on frontend/src/Views/CasesTableView.tsx
> +function CasesTableView({
Why change const to function?

2022-08-16 12:03 UTC, DanielBohme commented on frontend/src/Views/CasesTableView.tsx
> +function CasesTableView({
Was to have uniformity, but I see now that different "view" files use either const or function. Reverted back to const

2022-08-17 09:52 UTC, taustad commented on frontend/src/Views/CasesTableView.tsx
> +            const projectResult: Project = await (await GetCaseService()).updateCase(caseResult)
Why specify the type for projectResult?

2022-08-17 09:53 UTC, taustad approved these changes
LGTM

2022-08-17 10:32 UTC, merged